import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  variable: "--font-tajawal",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className={`${tajawal.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
